%% ECML 2018 graphs and tables
% Script for making figure showing the covariance between tested model
% performance and ELA features.
% 
% Created for ECML 2018 article.

%% load data

% file containing ECML statistics from Martin
ecmlFile = fullfile('exp', 'experiments', 'ECML2018', 'ecml_stat.mat');
actualFolder = pwd;
articleFolder = fullfile(actualFolder(1:end - 1 - length('surrogate-cmaes')), 'latex_scmaes', 'ecml2018paper');
plotResultsFolder = fullfile(articleFolder, 'images');
tableFolder = fullfile(articleFolder, 'tex');
if ~isdir(plotResultsFolder)
  mkdir(plotResultsFolder)
end
if ~isdir(tableFolder)
  mkdir(tableFolder)
end

% load Spearman correlation coefficients
S = load(ecmlFile, 'Models', 'NonConstantMetafeatures', 'CovarianceAnalysis');

% labels of models
modelLabels = {...
  'RF\_bag\_CART\_MSE', ...
  'RF\_bag\_CART\_DE', ...
  'RF\_bag\_SECRET\_MSE', ...
  'RF\_bag\_SECRET\_DE', ...
  'RF\_bag\_OC1\_MSE', ...
  'RF\_bag\_OC1\_DE', ...
  'RF\_bag\_PAIR\_MSE', ...
  'RF\_bag\_PAIR\_DE', ...
  'RF\_bag\_SUPPORT\_MSE', ...
  'RF\_bag\_SUPPORT\_DE', ...
  ...
  'RF\_gb\_CART\_Grad', ...
  'RF\_gb\_SECRET\_Grad', ...
  'RF\_gb\_OC1\_Grad', ...
  'RF\_gb\_PAIR\_Grad', ...
  'RF\_gb\_SUPPORT\_Grad', ...
  ...
  'GP\_SE', ...
  'GP\_Mat\_5/2', ...
  'GP\_Mat\_3/2', ...
  'GP\_Mat\_1/2', ...
  'GP\_RQ', ...
  'GP\_NN', ...
  'GP\_ADD', ...
};

generatedFeatureLabels = {...
  'basic.dim', ...
  'basic.observations', ...
  'basic.lower\_min', ...
  'basic.lower\_max', ...
  'basic.upper\_min', ...
  'basic.upper\_max', ...
  'basic.objective\_min', ...
  'basic.objective\_max', ...
  'basic.blocks\_min', ...
  'basic.blocks\_max', ...
  'basic.cells\_total', ...
  'basic.cells\_filled', ...
  'basic.minimize\_fun', ...
  'cm\_angle.dist\_ctr2best\_mean', ...
  'cm\_angle.dist\_ctr2best\_std', ...
  'cm\_angle.dist\_ctr2worst\_mean', ...
  'cm\_angle.dist\_ctr2worst\_std', ...
  'cm\_angle.angle\_mean', ...
  'cm\_angle.angle\_std', ...
  'cm\_angle.y\_best2worst\_mean', ...
  'cm\_angle.y\_best2worst\_std', ...
  'cm\_convexity.concave\_soft', ...
  'cm\_convexity.concave\_hard', ...
  'cm\_convexity.convex\_soft', ...
  'cm\_convexity.convex\_hard', ...
  'cm\_gradhomo.grad\_mean', ...
  'cm\_gradhomo.grad\_std', ...
  'dispersion.ratio\_mean\_02', ...
  'dispersion.ratio\_median\_02', ...
  'dispersion.diff\_mean\_02', ...
  'dispersion.diff\_median\_02', ...
  'dispersion.ratio\_mean\_05', ...
  'dispersion.ratio\_median\_05', ...
  'dispersion.diff\_mean\_05', ...
  'dispersion.diff\_median\_05', ...
  'dispersion.ratio\_mean\_10', ...
  'dispersion.ratio\_median\_10', ...
  'dispersion.diff\_mean\_10', ...
  'dispersion.diff\_median\_10', ...
  'dispersion.ratio\_mean\_25', ...
  'dispersion.ratio\_median\_25', ...
  'dispersion.diff\_mean\_25', ...
  'dispersion.diff\_median\_25', ...
  'ela\_distribution.skewness', ...
  'ela\_distribution.kurtosis', ...
  'ela\_distribution.number\_of\_peaks', ...
  'ela\_levelset.mmce\_lda\_10', ...
  'ela\_levelset.mmce\_qda\_10', ...
  'ela\_levelset.mmce\_mda\_10', ...
  'ela\_levelset.lda\_qda\_10', ...
  'ela\_levelset.lda\_mda\_10', ...
  'ela\_levelset.qda\_mda\_10', ...
  'ela\_levelset.mmce\_lda\_25', ...
  'ela\_levelset.mmce\_qda\_25', ...
  'ela\_levelset.mmce\_mda\_25', ...
  'ela\_levelset.lda\_qda\_25', ...
  'ela\_levelset.lda\_mda\_25', ...
  'ela\_levelset.qda\_mda\_25', ...
  'ela\_levelset.mmce\_lda\_50', ...
  'ela\_levelset.mmce\_qda\_50', ...
  'ela\_levelset.mmce\_mda\_50', ...
  'ela\_levelset.lda\_qda\_50', ...
  'ela\_levelset.lda\_mda\_50', ...
  'ela\_levelset.qda\_mda\_50', ...
  'ela\_metamodel.lin\_simple\_adj\_r2', ...
  'ela\_metamodel.lin\_simple\_intercept', ...
  'ela\_metamodel.lin\_simple\_coef\_min', ...
  'ela\_metamodel.lin\_simple\_coef\_max', ...
  'ela\_metamodel.lin\_simple\_coef\_max\_by\_min', ...
  'ela\_metamodel.lin\_w\_interact\_adj\_r2', ...
  'ela\_metamodel.quad\_simple\_adj\_r2', ...
  'ela\_metamodel.quad\_simple\_cond', ...
  'ela\_metamodel.quad\_w\_interact\_adj\_r2', ...
  'infocontent.h\_max', ...
  'infocontent.eps\_s', ...
  'infocontent.eps\_max', ...
  'infocontent.m0', ...
  'infocontent.eps\_ratio', ...
  'nearest\_better.nb\_std\_ratio', ...
  'nearest\_better.nb\_mean\_ratio', ...
  'nearest\_better.nb\_cor', ...
  'nearest\_better.dist\_ratio', ...
  'nearest\_better.nb\_fitness\_cor', ...
  'pca.pca\_cov\_x', ...
  'pca.pca\_corr\_x', ...
  'pca.pca\_cov\_init', ...
  'pca.pca\_corr\_init', ...
  'pca.pca\_pc1\_cov\_x', ...
  'pca.pca\_pc1\_corr\_x', ...
  'pca.pca\_pc1\_cov\_init', ...
  'pca.pca\_pc1\_corr\_init', ...
};

% use only non-constant metafeatures
featureLabels = generatedFeatureLabels(S.NonConstantMetafeatures);
nFeatures = numel(S.NonConstantMetafeatures);
nModels = numel(S.Models);

%% Spearman coefficients
close all

labelRot = 60;
sizeX = 20;
sizeY = 30;
plotNames = {'spearman'}; % , 'spearman_leg' , 'significance'};

clear pdfNames
pdfNames = {};
for p = 1:numel(plotNames)
  pdfNames{end+1} = fullfile(plotResultsFolder, sprintf('%s', plotNames{p}));
end


spearmanModel = zeros(nFeatures, nModels);
for m = 1:nModels
  spearmanModel(:, m) = S.Models(m).Spearman';
end
% draw coeffs without colorbar
han{1} = figure('Units', 'centimeters', ...
                'Position', [1 1 sizeX sizeY], ...
                'PaperSize', [sizeX + 2 32]);
% subplot(2, 2, 1)
imagesc(spearmanModel);
colorbar
% axis square
ax = gca;
ax.YTick = 1:nFeatures;
ax.YTickLabel = featureLabels;
ax.XTick = 1:nModels;
ax.XTickLabel = modelLabels;
ax.XTickLabelRotation = labelRot;

% % draw coeffs due to colorbar
% han{2} = figure('Units', 'centimeters', 'Position', [1 1 sizeX sizeY]);
% imagesc(spearmanModel);
% colorbar
% axis square

% % draw significance
% slopeSign = reshape(S.CovarianceAnalysis.SignificanceHolmSlopes, nModels, nFeatures)';
% % interSign = logical(randi(2, nFeatures, nModels));
% % significance numbers:
% % 0 - no sign
% % 1 - slope sign
% % 2 - inter sign
% % 3 - both sign
% signColor = slopeSign; % + 2*interSign;
% % draw
% han{3} = figure('Units', 'centimeters', ...
%                 'Position', [1 1 sizeX sizeY], ...
%                 'PaperSize', [sizeX + 2 32]);
% % subplot(2, 2, 2)
% imagesc(signColor);
% colormap(gray(2))
% % axis square
% grid on
% % colorbar
% ax = gca;
% ax.YTick = 1:nFeatures;
% ax.YTickLabel = featureLabels;
% ax.XTick = 1:nModels;
% ax.XTickLabel = modelLabels;
% ax.XTickLabelRotation = labelRot;

print2pdf(han, pdfNames, 1)