function [gain] = gainMse(current, left, right)
  gain = immse(current.y, current.yPred) - (...
    immse(left.y, left.yPred) * numel(left.y) ...
    + ...
    immse(right.y, right.yPred) * numel(right.y) ...
  ) / (numel(left.y) + numel(right.y));
end