function htmlPostProc(filename)
% htmlPostProc(filename) runs post-processing of html file generated by
% publish function. Imports external html files created while running
% generateReport.
%
% Input:
%   filename - name of html file to process
% 
% See Also:
%   publish, generateReport

  if nargin < 1
    help htmlPostProc
    return
  end
  
  % import tag
  iTag = 'importhtml';
  [sourcePath, nameOfFile, ext] = fileparts(filename);
  % load content
  content = fileread(filename);
  % find all import tag identifiers and filenames
  [iTagStartId, iTagEndId, htmlFiles] = regexp(content, ['<p>.?<', iTag,' s="(\w+).html"></', iTag, '>.?</p>'], 'start', 'end', 'tokens');
  
  % import tag exists
  if ~isempty(iTagStartId)
    % temporary file name
    tmpFile = fullfile(sourcePath, [nameOfFile, '_tmp', ext]);
    % open temporary html file
    FID = fopen(tmpFile, 'w');

    contentId = 1;
    % replace all import tags by content of imported files
    for ti = 1:length(iTagStartId)
      % copy old content to new tagID
      fprintf(FID, '%s', content(contentId : iTagStartId(ti) - 1));
      % load htmlfile content
      htmlContent = fileread(fullfile(sourcePath, [htmlFiles{ti}{1}, '.html']));
      % copy htmlfile content
      fprintf(FID, '%s', htmlContent);
      % check if the image follows
      if strcmp(content(iTagEndId(ti)+1 : iTagEndId(ti)+4), '<img')
        % skip image tag
        brackId = strfind(content(iTagEndId(ti) + 1:end), '>');
        contentId = iTagEndId(ti) + brackId(1) + 1;
      else
        % continue without interruption
        contentId = iTagEndId(ti) + 1;
      end
    end

    % finish temporary document
    fprintf(FID, '%s', content(contentId:end));

    % close temporary html
    fclose(FID);
    % replace original file by temporary
    copyfile(tmpFile, filename);
    % remove temporary file
    delete(tmpFile)
  end

end