%% Separate functions
for f = funcSet.BBfunc
  han = relativeFValuesPlot(data, ...
                            'DataDims', funcSet.dims, ...
                            'DataFuns', funcSet.BBfunc, ...
                            'PlotFuns', f, ...
                            'AggregateDims', false, ...
                            'AggregateFuns', false, ...
                            'DataNames', datanames, ...
                            'Colors', colors, ...
                            'FunctionNames', true, ...
                            'LineWidth', 1, ...
                            'Statistic', @median);
end

%% Final results for each dimension

han = relativeFValuesPlot(data, ...
'DataDims', funcSet.dims, ...
'DataFuns', funcSet.BBfunc, ...
'AggregateDims', false, ...
'AggregateFuns', true, ...
'DataNames', datanames, ...
'Colors', colors, ...
'FunctionNames', true, ...
'LineWidth', 1.5, ...
'Statistic', @median);
